Added Regression test for IS-147

diff --git a/certification/test-BDII-site b/certification/test-BDII-site
--- a/certification/test-BDII-site
+++ b/certification/test-BDII-site
@@ -265,6 +265,16 @@ else
     echo "OK"
 fi 
 
+echo -n "Regression Test for IS-147: Checking Country is only the Country: "
+filter="(&(objectClass=GLUE2Location)(GLUE2LocationCountry=Country))"
+${command} ${bind} ${filter} | grep Country >/dev/null 2>/dev/null
+if [ $? -gt 0 ]; then
+    echo "FAIL"
+    RETVAL=1
+else
+    echo "OK"
+fi 
+
 if [ ${RETVAL} -eq 1 ]; then
     echo "Test Failed"
     exit 1
