Solved tickets #203 and #204

diff --git a/glite-info-create/glite-into-create-core/trunk/sbin/glite-info-create b/glite-info-create/glite-into-create-core/trunk/sbin/glite-info-create
--- a/glite-info-create/glite-into-create-core/trunk/sbin/glite-info-create
+++ b/glite-info-create/glite-into-create-core/trunk/sbin/glite-info-create
@@ -32,17 +32,19 @@
 function print_help() {
   cat << EOF >&2
 Usage:
-  glite-info-create.sh -m <module> [-i <iface>] [-t <templates>] [-c <config>]
+  glite-info-create.sh -m <module> [-i <ifaces>] [-t <templates>]
+                      [-c <configs>] [-p <path>]
        
 Parameters:
   <module>    The module you are using. E.g.: site
-  <iface>     The interface you want to use. E.g.: glue, wlcg (default)
+  <ifaces>    The interface you want to use. E.g.: glue, wlcg (default)
   <templates> The template you want to use. E.g.: glue1, glue2 (all default)
-  <config>    The config file location if outside from the module directory
+  <configs>   The config file location if outside from the module directory
+  <path>      The path for the module directory. Default: /etc/glite-info-create/
 
 Examples:
   glite-info-create.sh -m site
-  glite-info-create.sh -m site -i glue -t glue2 -c /etc/bdii/site.cfg
+  glite-info-create.sh -m site -i 'glue wlcg' -t glue2 -c /etc/site.cfg
 
 Web site: http://cern.ch/gridinfo
 EOF
@@ -51,30 +53,32 @@ EOF
 # 1. Basic setup
 `unalias -a` # Remove all aliases from this new shell
 STARTTIME=`date +%s`
-VERSION='0.3'
+VERSION='0.4'
 echo "Welcome to gLite Info Static Create v$VERSION"
-abspath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
-echo "Changing to $abspath"
-cd `dirname $abspath`
+#fullpath="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
 if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "-help" ] || [ "$1" = "--help" ]; then
   print_help
   exit 1
 fi
 
 # 2. Set default values and parse command line arguments
-interface='wlcg'
+interfaces='wlcg'
 templates='glue1 glue2'
 ldif_files=''
-while getopts ":m:i:t:c:" opt; do
+fullpath=/etc/glite-info-create
+while getopts ":m:i:t:c:p:" opt; do
   case $opt in
-    i) interface=$OPTARG;;
+    i) interfaces=$OPTARG;;
     t) templates=$OPTARG;;
     c) config_files=$OPTARG;;
     m) module=$OPTARG;;
+    p) fullpath=$OPTARG;;
     \?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
     :) echo "Option -$OPTARG requires an argument." >&2; exit 1;;
   esac
 done
+echo "Changing to $fullpath"
+cd $fullpath
 
 if [ -z $module ]; then
   print_help; 
@@ -82,7 +86,6 @@ if [ -z $module ]; then
   exit 1;
 fi
 if [ -z $config_files ]; then config_files="$module.*.cfg"; fi
-echo $config_files
 
 # 3. Source the config file
 for config_file in $config_files; do
@@ -91,36 +94,40 @@ for config_file in $config_files; do
     exit 1
   fi
   source $config_file
-  echo "CONFIG: $config_file"
+  echo "DEBUG: Using config file $config_file"
 
   # 4. Check all needed variables are present using the interface
-  interface_file=$module/$module.$interface.ifc
-  if [ ! -f $interface_file ]; then
-    echo "ERROR: $interface_file is not a valid interface file"
-    exit 1
-  fi
-  source $interface_file
-  MANDATORY_VARS="$MANDATORY_SINGLEVALUED_VARS $MANDATORY_MULTIVALUED_VARS"
-  OPTIONAL_VARS="$OPTIONAL_SINGLEVALUED_VARS $OPTIONAL_MULTIVALUED_VARS"
-  MULTIVALUED_VARS="$MANDATORY_MULTIVALUED_VARS $OPTIONAL_MULTIVALUED_VARS"
-  SINGLEVALUED_VARS="$MANDATORY_SINGLEVALUED_VARS $OPTIONAL_SINGLEVALUED_VARS"
-  for var in $MANDATORY_VARS; do
-    eval val=\$$var
-    if [ "x$val" = "x" ]; then
-      echo "ERROR: $var has no value. Check $config_file"
-      echo "Mandatory values: $MANDATORY_VARS"
-      echo "Optional values: $OPTIONAL_VARS"
+  for interface in $interfaces; do
+    interface_file="$module/$module.$interface.ifc"
+    echo "DEBUG: Checking interface $interface_file"
+    if [ ! -f $interface_file ]; then
+      echo "ERROR: $interface_file is not a valid interface file"
       exit 1
     fi
-  done
-  for var in $OPTIONAL_VARS; do
-    eval val=\$$var
-    if [ "x$val" = "x" ]; then
-      echo "WARNING: $var has no value. Fix it in $config_file"
-    fi
+    source $interface_file
+    MANDATORY_VARS="$MANDATORY_SINGLEVALUED_VARS $MANDATORY_MULTIVALUED_VARS"
+    OPTIONAL_VARS="$OPTIONAL_SINGLEVALUED_VARS $OPTIONAL_MULTIVALUED_VARS"
+    MULTIVALUED_VARS="$MANDATORY_MULTIVALUED_VARS $OPTIONAL_MULTIVALUED_VARS"
+    SINGLEVALUED_VARS="$MANDATORY_SINGLEVALUED_VARS $OPTIONAL_SINGLEVALUED_VARS"
+    for var in $MANDATORY_VARS; do
+      eval val=\$$var
+      if [ "x$val" = "x" ]; then
+        echo "ERROR: $var has no value. Check $config_file"
+        echo "Mandatory values: $MANDATORY_VARS"
+        echo "Optional values: $OPTIONAL_VARS"
+        exit 1
+      fi
+    done
+    for var in $OPTIONAL_VARS; do
+      eval val=\$$var
+      if [ "x$val" = "x" ]; then
+        echo "WARNING: $var has no value. Fix it in $config_file"
+      fi
+    done
   done
 
   # 5. Fill the templates so all variables are filled
+  echo "DEBUG: Generating files"
   for template in $templates; do
     template_file=$module/$module.$template.tpl
     if [ ! -f $template_file ]; then
