Started to add glue 2.0 tests

diff --git a/glite-info-provider-ldap/trunk/test/run-tests b/glite-info-provider-ldap/trunk/test/run-tests
--- a/glite-info-provider-ldap/trunk/test/run-tests
+++ b/glite-info-provider-ldap/trunk/test/run-tests
@@ -74,6 +74,24 @@ else
     echo "OK"
 fi
 
+echo -n "Testing site-level operation for glue 2.0 ... "
+echo "${command} -c ${working_dir}/config/site.conf -g -m Test-Site | grep gservice_1 >/dev/null"
+if [ $? -gt 0 ]; then 
+    echo "Fail"
+    RETVAL=1
+else
+    echo "OK"
+fi
+
+echo -n "Testing massaging resource dn for glue 2.0 ... "
+${command} -c ${working_dir}/config/site.conf -g -m Test-Site | grep Test-Site >/dev/null
+if [ $? -gt 0 ]; then 
+    echo "Fail"
+    RETVAL=1
+else
+    echo "OK"
+fi
+
 echo "Stopping SLAPD ... "
 kill $(cat ${working_dir}/db/slapd.pid)
 
